// Copyright 2026 sidhartha1s. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type AddGuestToFolderresponse struct {
	Guest json.RawMessage `json:"guest"`
}

type AddGuestToListresponse struct {
	Guest json.RawMessage `json:"guest"`
}

type AddGuestToTaskresponse struct {
	Guest json.RawMessage `json:"guest"`
}

type AddTaskLinkresponse struct {
	Task json.RawMessage `json:"task"`
}

type ChecklistDeleteResponse struct {
}

type ChecklistEditResponse struct {
}

type ChecklistItemDeleteResponse struct {
}

type CommentDeleteResponse struct {
}

type CommentUpdateResponse struct {
}

type CreateChatViewCommentresponse struct {
	Date int `json:"date"`
	HistId string `json:"hist_id"`
	Id string `json:"id"`
}

type CreateChecklistItemresponse struct {
	Checklist json.RawMessage `json:"checklist"`
}

type CreateChecklistresponse struct {
	Checklist json.RawMessage `json:"checklist"`
}

type CreateFolderViewresponse struct {
	View string `json:"view"`
}

type CreateFolderlessListresponse struct {
	Assignee json.RawMessage `json:"assignee"`
	Content string `json:"content"`
	DueDate string `json:"due_date"`
	DueDateTime bool `json:"due_date_time"`
	Folder json.RawMessage `json:"folder"`
	Id string `json:"id"`
	InboundAddress string `json:"inbound_address"`
	Name string `json:"name"`
	Orderindex int `json:"orderindex"`
	Priority json.RawMessage `json:"priority"`
	Space json.RawMessage `json:"space"`
	StartDate string `json:"start_date"`
	StartDateTime string `json:"start_date_time"`
	Status json.RawMessage `json:"status"`
	Statuses json.RawMessage `json:"statuses"`
	TaskCount string `json:"task_count"`
}

type CreateFolderresponse struct {
	Hidden bool `json:"hidden"`
	Id string `json:"id"`
	Name string `json:"name"`
	Orderindex int `json:"orderindex"`
	OverrideStatuses bool `json:"override_statuses"`
	Space json.RawMessage `json:"space"`
	TaskCount string `json:"task_count"`
}

type CreateGoalresponse struct {
	Goal json.RawMessage `json:"goal"`
}

type CreateKeyResultresponse struct {
	KeyResult json.RawMessage `json:"key_result"`
}

type CreateListCommentresponse struct {
	Date int `json:"date"`
	HistId string `json:"hist_id"`
	Id string `json:"id"`
}

type CreateListViewresponse struct {
	View string `json:"view"`
}

type CreateListresponse struct {
	Assignee json.RawMessage `json:"assignee"`
	Content string `json:"content"`
	DueDate string `json:"due_date"`
	DueDateTime bool `json:"due_date_time"`
	Folder json.RawMessage `json:"folder"`
	Id string `json:"id"`
	InboundAddress string `json:"inbound_address"`
	Name string `json:"name"`
	Orderindex int `json:"orderindex"`
	Priority json.RawMessage `json:"priority"`
	Space json.RawMessage `json:"space"`
	StartDate string `json:"start_date"`
	StartDateTime string `json:"start_date_time"`
	Status json.RawMessage `json:"status"`
	Statuses json.RawMessage `json:"statuses"`
	TaskCount string `json:"task_count"`
}

type CreateSpaceViewresponse struct {
	View string `json:"view"`
}

type CreateSpaceresponse struct {
	Archived bool `json:"archived"`
	Features json.RawMessage `json:"features"`
	Id string `json:"id"`
	MultipleAssignees bool `json:"multiple_assignees"`
	Name string `json:"name"`
	Private bool `json:"private"`
	Statuses json.RawMessage `json:"statuses"`
}

type CreateTaskAttachmentresponse struct {
	Date int `json:"date"`
	Extension string `json:"extension"`
	Id string `json:"id"`
	ThumbnailLarge string `json:"thumbnail_large"`
	ThumbnailSmall string `json:"thumbnail_small"`
	Title string `json:"title"`
	Url string `json:"url"`
	Version string `json:"version"`
}

type CreateTaskCommentresponse struct {
	Date int `json:"date"`
	HistId string `json:"hist_id"`
	Id string `json:"id"`
}

type CreateTaskresponseYaml struct {
	Archived bool `json:"archived"`
	Assignees json.RawMessage `json:"assignees"`
	Checklists json.RawMessage `json:"checklists"`
	Creator json.RawMessage `json:"creator"`
	CustomFields json.RawMessage `json:"custom_fields"`
	CustomId string `json:"custom_id"`
	CustomItemId float64 `json:"custom_item_id"`
	DateClosed string `json:"date_closed"`
	DateCreated string `json:"date_created"`
	DateDone string `json:"date_done"`
	DateUpdated string `json:"date_updated"`
	Dependencies json.RawMessage `json:"dependencies"`
	Description string `json:"description"`
	DueDate string `json:"due_date"`
	Folder json.RawMessage `json:"folder"`
	GroupAssignees json.RawMessage `json:"group_assignees"`
	Id string `json:"id"`
	LinkedTasks json.RawMessage `json:"linked_tasks"`
	List json.RawMessage `json:"list"`
	Locations json.RawMessage `json:"locations"`
	MarkdownDescription string `json:"markdown_description"`
	Name string `json:"name"`
	Orderindex string `json:"orderindex"`
	Parent string `json:"parent"`
	PermissionLevel string `json:"permission_level"`
	Points float64 `json:"points"`
	Priority json.RawMessage `json:"priority"`
	Project json.RawMessage `json:"project"`
	Sharing json.RawMessage `json:"sharing"`
	Space json.RawMessage `json:"space"`
	StartDate string `json:"start_date"`
	Status json.RawMessage `json:"status"`
	Tags json.RawMessage `json:"tags"`
	TeamId string `json:"team_id"`
	TextContent string `json:"text_content"`
	TimeEstimate string `json:"time_estimate"`
	TimeSpent float64 `json:"time_spent"`
	TopLevelParent string `json:"top_level_parent"`
	Url string `json:"url"`
	Watchers json.RawMessage `json:"watchers"`
}

type CreateTeamViewresponse struct {
	View string `json:"view"`
}

type CreateTeamresponse struct {
	Avatar json.RawMessage `json:"avatar"`
	DateCreated string `json:"date_created"`
	Handle string `json:"handle"`
	Id string `json:"id"`
	Initials string `json:"initials"`
	Members json.RawMessage `json:"members"`
	Name string `json:"name"`
	TeamId string `json:"team_id"`
	Userid int `json:"userid"`
}

type CreateWebhookresponse struct {
	Id string `json:"id"`
	Webhook json.RawMessage `json:"webhook"`
}

type Createatimeentryresponse struct {
	Assignee int `json:"assignee"`
	Billable bool `json:"billable"`
	Description string `json:"description"`
	Duration int `json:"duration"`
	Start int `json:"start"`
	Tags json.RawMessage `json:"tags"`
	Tid string `json:"tid"`
}

type Data1 struct {
	Creator int `json:"creator"`
	Name string `json:"name"`
	TagBg string `json:"tag_bg"`
	TagFg string `json:"tag_fg"`
}

type Datum struct {
	Intervals json.RawMessage `json:"intervals"`
	Time int `json:"time"`
	User json.RawMessage `json:"user"`
}

type Datum1 struct {
	Approval json.RawMessage `json:"approval"`
	ApprovalId string `json:"approval_id"`
	At string `json:"at"`
	Billable bool `json:"billable"`
	Description string `json:"description"`
	Duration string `json:"duration"`
	End string `json:"end"`
	Id string `json:"id"`
	Source string `json:"source"`
	Start string `json:"start"`
	Tags json.RawMessage `json:"tags"`
	Task json.RawMessage `json:"task"`
	TaskLocation json.RawMessage `json:"task_location"`
	TaskTags json.RawMessage `json:"task_tags"`
	TaskUrl string `json:"task_url"`
	User json.RawMessage `json:"user"`
	Wid string `json:"wid"`
}

type DeleteTaskLinkresponse struct {
	Task json.RawMessage `json:"task"`
}

type DeleteatimeEntryresponse struct {
	Data json.RawMessage `json:"data"`
}

type DependencyAddResponse struct {
}

type DependencyDeleteResponse struct {
}

type EditChecklistItemresponse struct {
	Checklist json.RawMessage `json:"checklist"`
}

type EditGuestOnWorkspaceresponse struct {
	Guest json.RawMessage `json:"guest"`
}

type EditKeyResultresponse struct {
	KeyResult json.RawMessage `json:"key_result"`
}

type EditSpaceTagresponse struct {
	Tag json.RawMessage `json:"tag"`
}

type EditUserOnWorkspaceresponse struct {
	Member json.RawMessage `json:"member"`
}

type FieldRemoveCustomValueResponse struct {
}

type FieldSetCustomValueResponse struct {
}

type FolderDeleteResponse struct {
}

type FolderTemplateCreateFolderFromTemplateResponse struct {
	Folder json.RawMessage `json:"folder"`
	Id int `json:"id"`
}

type GetAccessTokenresponse struct {
	AccessToken string `json:"access_token"`
}

type GetAccessibleCustomFieldsresponse struct {
	Fields json.RawMessage `json:"fields"`
}

type GetAuthorizedTeamsresponse struct {
	Teams json.RawMessage `json:"teams"`
}

type GetAuthorizedUserresponse struct {
	User json.RawMessage `json:"user"`
}

type GetBulkTasksTimeinStatusresponse struct {
	V20bbn28 json.RawMessage `json:"20bbn28"`
	V27075wz json.RawMessage `json:"27075wz"`
}

type GetChatViewCommentsresponse struct {
	Comments json.RawMessage `json:"comments"`
}

type GetCustomItemsResponse struct {
	CustomItems json.RawMessage `json:"custom_items"`
}

type GetCustomRolesresponse struct {
	CustomRoles json.RawMessage `json:"custom_roles"`
}

type GetFilteredTeamTasksresponse struct {
	Tasks json.RawMessage `json:"tasks"`
}

type GetFolderAvailableFieldsresponse struct {
	Fields json.RawMessage `json:"fields"`
}

type GetFolderTemplatesresponse struct {
	Templates json.RawMessage `json:"templates"`
}

type GetFolderViewsresponse struct {
	Views json.RawMessage `json:"views"`
}

type GetFolderlessListsresponse struct {
	Lists json.RawMessage `json:"lists"`
}

type GetFolderresponse struct {
	Hidden bool `json:"hidden"`
	Id string `json:"id"`
	Lists json.RawMessage `json:"lists"`
	Name string `json:"name"`
	Orderindex int `json:"orderindex"`
	OverrideStatuses bool `json:"override_statuses"`
	Space json.RawMessage `json:"space"`
	TaskCount string `json:"task_count"`
}

type GetFoldersresponse struct {
	Folders json.RawMessage `json:"folders"`
}

type GetGoalresponse struct {
	Goal json.RawMessage `json:"goal"`
}

type GetGoalsresponse struct {
	Folders json.RawMessage `json:"folders"`
	Goals json.RawMessage `json:"goals"`
}

type GetListCommentsresponse struct {
	Comments json.RawMessage `json:"comments"`
}

type GetListMembersresponse struct {
	Members json.RawMessage `json:"members"`
}

type GetListTemplatesresponse struct {
	Templates json.RawMessage `json:"templates"`
}

type GetListViewsresponse struct {
	Views json.RawMessage `json:"views"`
}

type GetListresponse struct {
	Archived bool `json:"archived"`
	Assignee string `json:"assignee"`
	Content string `json:"content"`
	DueDate string `json:"due_date"`
	DueDateTime bool `json:"due_date_time"`
	Folder json.RawMessage `json:"folder"`
	Id string `json:"id"`
	InboundAddress string `json:"inbound_address"`
	Name string `json:"name"`
	Orderindex int `json:"orderindex"`
	OverrideStatuses bool `json:"override_statuses"`
	PermissionLevel string `json:"permission_level"`
	Priority json.RawMessage `json:"priority"`
	Space json.RawMessage `json:"space"`
	StartDate string `json:"start_date"`
	StartDateTime string `json:"start_date_time"`
	Status json.RawMessage `json:"status"`
	Statuses json.RawMessage `json:"statuses"`
	TaskCount string `json:"task_count"`
}

type GetListsresponse struct {
	Lists json.RawMessage `json:"lists"`
}

type GetSpaceAvailableFieldsresponse struct {
	Fields json.RawMessage `json:"fields"`
}

type GetSpaceTagsresponse struct {
	Tags json.RawMessage `json:"tags"`
}

type GetSpaceViewsresponse struct {
	Views json.RawMessage `json:"views"`
}

type GetSpaceresponse struct {
	Features json.RawMessage `json:"features"`
	Id string `json:"id"`
	MultipleAssignees bool `json:"multiple_assignees"`
	Name string `json:"name"`
	Private bool `json:"private"`
	Statuses json.RawMessage `json:"statuses"`
}

type GetSpacesresponse struct {
	Spaces json.RawMessage `json:"spaces"`
}

type GetTaskCommentsresponse struct {
	Comments json.RawMessage `json:"comments"`
}

type GetTaskMembersresponse struct {
	Members json.RawMessage `json:"members"`
}

type GetTaskTemplatesresponse struct {
	Templates json.RawMessage `json:"templates"`
}

type GetTaskresponse struct {
	Archived bool `json:"archived"`
	Assignees json.RawMessage `json:"assignees"`
	Attachments json.RawMessage `json:"attachments"`
	Checklists json.RawMessage `json:"checklists"`
	Creator json.RawMessage `json:"creator"`
	CustomFields json.RawMessage `json:"custom_fields"`
	CustomId string `json:"custom_id"`
	CustomItemId float64 `json:"custom_item_id"`
	DateClosed string `json:"date_closed"`
	DateCreated string `json:"date_created"`
	DateDone string `json:"date_done"`
	DateUpdated string `json:"date_updated"`
	Dependencies json.RawMessage `json:"dependencies"`
	Description string `json:"description"`
	DueDate string `json:"due_date"`
	Folder json.RawMessage `json:"folder"`
	GroupAssignees json.RawMessage `json:"group_assignees"`
	Id string `json:"id"`
	LinkedTasks json.RawMessage `json:"linked_tasks"`
	List json.RawMessage `json:"list"`
	Locations json.RawMessage `json:"locations"`
	MarkdownDescription string `json:"markdown_description"`
	Name string `json:"name"`
	Orderindex string `json:"orderindex"`
	Parent string `json:"parent"`
	PermissionLevel string `json:"permission_level"`
	Points float64 `json:"points"`
	Priority json.RawMessage `json:"priority"`
	Project json.RawMessage `json:"project"`
	Sharing json.RawMessage `json:"sharing"`
	Space json.RawMessage `json:"space"`
	StartDate string `json:"start_date"`
	Status json.RawMessage `json:"status"`
	Subtasks json.RawMessage `json:"subtasks"`
	Tags json.RawMessage `json:"tags"`
	TeamId string `json:"team_id"`
	TextContent string `json:"text_content"`
	TimeEstimate float64 `json:"time_estimate"`
	TimeSpent float64 `json:"time_spent"`
	TopLevelParent string `json:"top_level_parent"`
	Url string `json:"url"`
	Watchers json.RawMessage `json:"watchers"`
}

type GetTasksTimeinStatusresponse struct {
	CurrentStatus json.RawMessage `json:"current_status"`
	StatusHistory json.RawMessage `json:"status_history"`
}

type GetTasksresponse struct {
	LastPage bool `json:"last_page"`
	Tasks json.RawMessage `json:"tasks"`
}

type GetTeamAvailableFieldsresponse struct {
	Fields json.RawMessage `json:"fields"`
}

type GetTeamViewsresponse struct {
	Views json.RawMessage `json:"views"`
}

type GetTeamsresponse struct {
	Groups json.RawMessage `json:"groups"`
}

type GetUserresponse struct {
	Member json.RawMessage `json:"member"`
}

type GetViewTasksresponse struct {
	LastPage bool `json:"last_page"`
	Tasks json.RawMessage `json:"tasks"`
}

type GetWebhooksresponse struct {
	Webhooks json.RawMessage `json:"webhooks"`
}

type GetWorkspaceplanresponse struct {
	PlanId int `json:"plan_id"`
	PlanName string `json:"plan_name"`
}

type GetWorkspaceseatsresponse struct {
	Guests json.RawMessage `json:"guests"`
	Members json.RawMessage `json:"members"`
}

type Getrunningtimeentryresponse struct {
	Data json.RawMessage `json:"data"`
}

type Getsingulartimeentryresponse struct {
	Data json.RawMessage `json:"data"`
}

type GoalDeleteResponse struct {
}

type GroupDeleteTeamResponse struct {
}

type GuestGetResponse struct {
}

type InviteGuestToWorkspaceresponse struct {
	Team json.RawMessage `json:"team"`
}

type InviteUserToWorkspaceresponse struct {
	Team json.RawMessage `json:"team"`
}

type KeyResultDeleteResponse struct {
}

type ListDeleteResponse struct {
}

type ListTemplateCreateSpaceListFromTemplateResponse struct {
	Id string `json:"id"`
	List json.RawMessage `json:"list"`
}

type RemoveGuestFromFolderresponse struct {
	Guest json.RawMessage `json:"guest"`
}

type RemoveGuestFromListresponse struct {
	Guest json.RawMessage `json:"guest"`
}

type RemoveGuestFromTaskresponse struct {
	Guest json.RawMessage `json:"guest"`
}

type RemoveGuestFromWorkspaceresponse struct {
	Team json.RawMessage `json:"team"`
}

type RemoveUserFromWorkspaceresponse struct {
	Team json.RawMessage `json:"team"`
}

type ReplyCreateThreadedCommentResponse struct {
}

type SharedHierarchyresponse struct {
	Shared json.RawMessage `json:"shared"`
}

type SpaceDeleteResponse struct {
}

type StartatimeEntryresponse struct {
	Data json.RawMessage `json:"data"`
}

type StopatimeEntryresponse struct {
	Data json.RawMessage `json:"data"`
}

type TagAddToTaskResponse struct {
}

type TagCreateSpaceResponse struct {
}

type TagDeleteSpaceResponse struct {
}

type TagRemoveFromTaskResponse struct {
}

type TaskAddToListResponse struct {
}

type TaskDeleteResponse struct {
}

type TaskRemoveFromListResponse struct {
}

type TaskTemplateCreateTaskFromTemplateResponse struct {
}

type TimeDeletetimetrackedResponse struct {
}

type TimeEdittimetrackedResponse struct {
}

type TimeEntriesAddtagsfromtimeentriesResponse struct {
}

type TimeEntriesChangetagnamesfromtimeentriesResponse struct {
}

type TimeEntriesGettimeentryhistoryResponse struct {
}

type TimeEntriesRemovetagsfromtimeentriesResponse struct {
}

type TimeEntriesUpdateatimeEntryResponse struct {
}

type Tracktimeresponse struct {
	Id string `json:"id"`
}

type UpdateFolderresponse struct {
	Hidden bool `json:"hidden"`
	Id string `json:"id"`
	Name string `json:"name"`
	Orderindex int `json:"orderindex"`
	OverrideStatuses bool `json:"override_statuses"`
	Space json.RawMessage `json:"space"`
	TaskCount string `json:"task_count"`
}

type UpdateGoalresponse struct {
	Goal json.RawMessage `json:"goal"`
}

type UpdateListresponse struct {
	Assignee string `json:"assignee"`
	Content string `json:"content"`
	DueDate string `json:"due_date"`
	DueDateTime bool `json:"due_date_time"`
	Folder json.RawMessage `json:"folder"`
	Id string `json:"id"`
	InboundAddress string `json:"inbound_address"`
	Name string `json:"name"`
	Orderindex int `json:"orderindex"`
	Priority json.RawMessage `json:"priority"`
	Space json.RawMessage `json:"space"`
	StartDate string `json:"start_date"`
	StartDateTime string `json:"start_date_time"`
	Status json.RawMessage `json:"status"`
	Statuses json.RawMessage `json:"statuses"`
	TaskCount string `json:"task_count"`
}

type UpdateSpaceresponse struct {
	Features json.RawMessage `json:"features"`
	Id string `json:"id"`
	MultipleAssignees bool `json:"multiple_assignees"`
	Name string `json:"name"`
	Private bool `json:"private"`
	Statuses json.RawMessage `json:"statuses"`
}

type UpdateTaskresponse struct {
	Archived bool `json:"archived"`
	Assignees json.RawMessage `json:"assignees"`
	Attachments json.RawMessage `json:"attachments"`
	Checklists json.RawMessage `json:"checklists"`
	Creator json.RawMessage `json:"creator"`
	CustomFields json.RawMessage `json:"custom_fields"`
	CustomId string `json:"custom_id"`
	CustomItemId float64 `json:"custom_item_id"`
	DateClosed string `json:"date_closed"`
	DateCreated string `json:"date_created"`
	DateDone string `json:"date_done"`
	DateUpdated string `json:"date_updated"`
	Dependencies json.RawMessage `json:"dependencies"`
	Description string `json:"description"`
	DueDate string `json:"due_date"`
	Folder json.RawMessage `json:"folder"`
	GroupAssignees json.RawMessage `json:"group_assignees"`
	Id string `json:"id"`
	LinkedTasks json.RawMessage `json:"linked_tasks"`
	List json.RawMessage `json:"list"`
	Locations json.RawMessage `json:"locations"`
	MarkdownDescription string `json:"markdown_description"`
	Name string `json:"name"`
	Orderindex string `json:"orderindex"`
	Parent string `json:"parent"`
	PermissionLevel string `json:"permission_level"`
	Points float64 `json:"points"`
	Priority json.RawMessage `json:"priority"`
	Project json.RawMessage `json:"project"`
	Sharing json.RawMessage `json:"sharing"`
	Space json.RawMessage `json:"space"`
	StartDate string `json:"start_date"`
	Status json.RawMessage `json:"status"`
	Subtasks json.RawMessage `json:"subtasks"`
	Tags json.RawMessage `json:"tags"`
	TeamId string `json:"team_id"`
	TextContent string `json:"text_content"`
	TimeEstimate string `json:"time_estimate"`
	TimeSpent float64 `json:"time_spent"`
	TopLevelParent string `json:"top_level_parent"`
	Url string `json:"url"`
	Watchers json.RawMessage `json:"watchers"`
}

type UpdateTeamresponse struct {
	Avatar json.RawMessage `json:"avatar"`
	DateCreated string `json:"date_created"`
	Handle string `json:"handle"`
	Id string `json:"id"`
	Initials string `json:"initials"`
	Members json.RawMessage `json:"members"`
	Name string `json:"name"`
	TeamId string `json:"team_id"`
	Userid int `json:"userid"`
}

type UpdateViewresponse struct {
	View string `json:"view"`
}

type UpdateWebhookresponse struct {
	Id string `json:"id"`
	Webhook json.RawMessage `json:"webhook"`
}

type ViewDeleteResponse struct {
}

type WebhookDeleteResponse struct {
}

type paths__1v2_1checklist_1_checklist_id__1checklist_item_1_checklist_item_id__put_responses_200_content_application_1json_schema_properties_checklist_properties_items_items struct {
	Assignee string `json:"assignee"`
	Children json.RawMessage `json:"children"`
	DateCreated string `json:"date_created"`
	Id string `json:"id"`
	Name string `json:"name"`
	Orderindex int `json:"orderindex"`
	Parent string `json:"parent"`
	Resolved bool `json:"resolved"`
}

type paths__1v2_1goal_1_goal_id__get_responses_200_content_application_1json_schema_properties_goal struct {
	Archived bool `json:"archived"`
	Color string `json:"color"`
	Creator int `json:"creator"`
	DateCreated string `json:"date_created"`
	Description string `json:"description"`
	DueDate string `json:"due_date"`
	FolderId string `json:"folder_id"`
	History json.RawMessage `json:"history"`
	Id string `json:"id"`
	KeyResults json.RawMessage `json:"key_results"`
	Members json.RawMessage `json:"members"`
	MultipleOwners bool `json:"multiple_owners"`
	Name string `json:"name"`
	Owners json.RawMessage `json:"owners"`
	PercentCompleted int `json:"percent_completed"`
	PrettyId string `json:"pretty_id"`
	PrettyUrl string `json:"pretty_url"`
	Private bool `json:"private"`
	StartDate string `json:"start_date"`
	TeamId string `json:"team_id"`
}

type paths__1v2_1goal_1_goal_id__get_responses_200_content_application_1json_schema_properties_goal_properties_owners_items struct {
	Color string `json:"color"`
	Email string `json:"email"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	ProfilePicture string `json:"profilePicture"`
	Username string `json:"username"`
}

type paths__1v2_1group_1_group_id__put_responses_200_content_application_1json_schema_properties_avatar struct {
	AttachmentId string `json:"attachment_id"`
	Color string `json:"color"`
	Icon string `json:"icon"`
	Source string `json:"source"`
}

type paths__1v2_1group_1_group_id__put_responses_200_content_application_1json_schema_properties_members_items struct {
	Color string `json:"color"`
	Email string `json:"email"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	ProfilePicture string `json:"profilePicture"`
	Username string `json:"username"`
}

type paths__1v2_1list_1_list_id__1field_get_responses_200_content_application_1json_schema_properties_fields_items struct {
	DateCreated string `json:"date_created"`
	HideFromGuests bool `json:"hide_from_guests"`
	Id string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
	TypeConfig json.RawMessage `json:"type_config"`
}

type paths__1v2_1list_1_list_id__get_responses_200_content_application_1json_schema_properties_folder struct {
	Access bool `json:"access"`
	Hidden bool `json:"hidden"`
	Id string `json:"id"`
	Name string `json:"name"`
}

type paths__1v2_1list_1_list_id__get_responses_200_content_application_1json_schema_properties_priority struct {
	Color string `json:"color"`
	Priority string `json:"priority"`
}

type paths__1v2_1list_1_list_id__get_responses_200_content_application_1json_schema_properties_space struct {
	Access bool `json:"access"`
	Id string `json:"id"`
	Name string `json:"name"`
}

type paths__1v2_1list_1_list_id__get_responses_200_content_application_1json_schema_properties_status struct {
	Color string `json:"color"`
	HideLabel bool `json:"hide_label"`
	Status string `json:"status"`
}

type paths__1v2_1oauth_1token_post_requestBody_content_application_1json_schema struct {
	ClientId string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	Code string `json:"code"`
}

type paths__1v2_1space_1_space_id__1list_get_responses_200_content_application_1json_schema_properties_lists_items struct {
	Archived bool `json:"archived"`
	Assignee string `json:"assignee"`
	Content string `json:"content"`
	DueDate string `json:"due_date"`
	Folder json.RawMessage `json:"folder"`
	Id string `json:"id"`
	Name string `json:"name"`
	Orderindex int `json:"orderindex"`
	OverrideStatuses bool `json:"override_statuses"`
	PermissionLevel string `json:"permission_level"`
	Priority string `json:"priority"`
	Space json.RawMessage `json:"space"`
	StartDate string `json:"start_date"`
	Status string `json:"status"`
	TaskCount string `json:"task_count"`
}

type paths__1v2_1space_1_space_id__1list_post_responses_200_content_application_1json_schema_properties_assignee struct {
	Color string `json:"color"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	ProfilePicture string `json:"profilePicture"`
	Username string `json:"username"`
}

type paths__1v2_1space_1_space_id__1list_template_1_template_id__post_requestBody_content_application_1json_schema_properties_options struct {
	Archived int `json:"archived"`
	Attachments bool `json:"attachments"`
	Automation bool `json:"automation"`
	Comment bool `json:"comment"`
	CommentAttachments bool `json:"comment_attachments"`
	Content string `json:"content"`
	CustomFields bool `json:"custom_fields"`
	CustomType bool `json:"custom_type"`
	DueDate string `json:"due_date"`
	ExternalDependencies bool `json:"external_dependencies"`
	IncludeViews bool `json:"include_views"`
	InternalDependencies bool `json:"internal_dependencies"`
	OldAssignees bool `json:"old_assignees"`
	OldChecklists bool `json:"old_checklists"`
	OldDueDate bool `json:"old_due_date"`
	OldFollowers bool `json:"old_followers"`
	OldStartDate bool `json:"old_start_date"`
	OldStatus bool `json:"old_status"`
	OldStatuses bool `json:"old_statuses"`
	OldSubtaskAssignees bool `json:"old_subtask_assignees"`
	OldTags bool `json:"old_tags"`
	Priority bool `json:"priority"`
	RecurSettings bool `json:"recur_settings"`
	Relationships bool `json:"relationships"`
	RemapStartDate bool `json:"remap_start_date"`
	ReturnImmediately bool `json:"return_immediately"`
	SkipWeekends bool `json:"skip_weekends"`
	StartDate string `json:"start_date"`
	Subtasks bool `json:"subtasks"`
	TimeEstimate float64 `json:"time_estimate"`
}

type paths__1v2_1space_1_space_id__1list_template_1_template_id__post_responses_200_content_application_1json_schema struct {
	Id string `json:"id"`
	List json.RawMessage `json:"list"`
}

type paths__1v2_1space_1_space_id__1tag_1_tag_name__put_requestBody_content_application_1json_schema_properties_tag struct {
	BgColor string `json:"bg_color"`
	FgColor string `json:"fg_color"`
	Name string `json:"name"`
}

type paths__1v2_1space_1_space_id__1tag_post_requestBody_content_application_1json_schema_properties_tag struct {
	Name string `json:"name"`
	TagBg string `json:"tag_bg"`
	TagFg string `json:"tag_fg"`
}

type paths__1v2_1space_1_space_id__put_requestBody_content_application_1json_schema_properties_features struct {
	Checklists json.RawMessage `json:"checklists"`
	CustomFields json.RawMessage `json:"custom_fields"`
	DependencyWarning json.RawMessage `json:"dependency_warning"`
	DueDates json.RawMessage `json:"due_dates"`
	Portfolios json.RawMessage `json:"portfolios"`
	RemapDependencies json.RawMessage `json:"remap_dependencies"`
	Tags json.RawMessage `json:"tags"`
	TimeEstimates json.RawMessage `json:"time_estimates"`
	TimeTracking json.RawMessage `json:"time_tracking"`
}

type paths__1v2_1space_1_space_id__put_requestBody_content_application_1json_schema_properties_features_properties_checklists struct {
	Enabled bool `json:"enabled"`
}

type paths__1v2_1space_1_space_id__put_requestBody_content_application_1json_schema_properties_features_properties_custom_fields struct {
	Enabled bool `json:"enabled"`
}

type paths__1v2_1space_1_space_id__put_requestBody_content_application_1json_schema_properties_features_properties_dependency_warning struct {
	Enabled bool `json:"enabled"`
}

type paths__1v2_1space_1_space_id__put_requestBody_content_application_1json_schema_properties_features_properties_due_dates struct {
	Enabled bool `json:"enabled"`
	RemapClosedDueDate bool `json:"remap_closed_due_date"`
	RemapDueDates bool `json:"remap_due_dates"`
	StartDate bool `json:"start_date"`
}

type paths__1v2_1space_1_space_id__put_requestBody_content_application_1json_schema_properties_features_properties_portfolios struct {
	Enabled bool `json:"enabled"`
}

type paths__1v2_1space_1_space_id__put_requestBody_content_application_1json_schema_properties_features_properties_remap_dependencies struct {
	Enabled bool `json:"enabled"`
}

type paths__1v2_1space_1_space_id__put_requestBody_content_application_1json_schema_properties_features_properties_tags struct {
	Enabled bool `json:"enabled"`
}

type paths__1v2_1space_1_space_id__put_requestBody_content_application_1json_schema_properties_features_properties_time_estimates struct {
	Enabled bool `json:"enabled"`
}

type paths__1v2_1space_1_space_id__put_requestBody_content_application_1json_schema_properties_features_properties_time_tracking struct {
	Enabled bool `json:"enabled"`
}

type paths__1v2_1task_1_task_id__1comment_get_responses_200_content_application_1json_schema struct {
	Comments json.RawMessage `json:"comments"`
}

type paths__1v2_1task_1_task_id__1comment_get_responses_200_content_application_1json_schema_properties_comments_items struct {
	AssignedBy json.RawMessage `json:"assigned_by"`
	Assignee json.RawMessage `json:"assignee"`
	Comment json.RawMessage `json:"comment"`
	CommentText string `json:"comment_text"`
	Date string `json:"date"`
	Id string `json:"id"`
	Reactions json.RawMessage `json:"reactions"`
	ReplyCount string `json:"reply_count"`
	Resolved bool `json:"resolved"`
	User json.RawMessage `json:"user"`
}

type paths__1v2_1task_1_task_id__1comment_get_responses_200_content_application_1json_schema_properties_comments_items_properties_assignee struct {
	Color string `json:"color"`
	Email string `json:"email"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	ProfilePicture string `json:"profilePicture"`
	Username string `json:"username"`
}

type paths__1v2_1task_1_task_id__1comment_get_responses_200_content_application_1json_schema_properties_comments_items_properties_comment_items struct {
	Text string `json:"text"`
}

type paths__1v2_1task_1_task_id__1comment_post_requestBody_content_application_1json_schema struct {
	Assignee int `json:"assignee"`
	CommentText string `json:"comment_text"`
	GroupAssignee string `json:"group_assignee"`
	NotifyAll bool `json:"notify_all"`
}

type paths__1v2_1task_1_task_id__1guest_1_guest_id__delete_responses_200_content_application_1json_schema_properties_guest struct {
	CanEditTags bool `json:"can_edit_tags"`
	CanSeeTimeEstimated bool `json:"can_see_time_estimated"`
	CanSeeTimeSpent bool `json:"can_see_time_spent"`
	InvitedBy json.RawMessage `json:"invited_by"`
	Shared json.RawMessage `json:"shared"`
	User json.RawMessage `json:"user"`
}

type paths__1v2_1task_1_task_id__1guest_1_guest_id__post_responses_200_content_application_1json_schema_properties_guest_properties_user struct {
	Color string `json:"color"`
	DateInvited string `json:"date_invited"`
	DateJoined string `json:"date_joined"`
	Email string `json:"email"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	LastActive string `json:"last_active"`
	ProfilePicture string `json:"profilePicture"`
	Role int `json:"role"`
	Username string `json:"username"`
}

type paths__1v2_1task_1_task_id__1member_get_responses_200_content_application_1json_schema_properties_members_items struct {
	Color string `json:"color"`
	Email string `json:"email"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	ProfileInfo json.RawMessage `json:"profileInfo"`
	ProfilePicture string `json:"profilePicture"`
	Username string `json:"username"`
}

type paths__1v2_1task_1_task_id__1time_get_responses_200_content_application_1json_schema_properties_data_items_properties_user struct {
	Color string `json:"color"`
	Email string `json:"email"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	ProfilePicture string `json:"profilePicture"`
	Username string `json:"username"`
}

type paths__1v2_1task_1_task_id__1time_in_status_get_responses_200_content_application_1json_schema_properties_current_status struct {
	Color string `json:"color"`
	Status string `json:"status"`
	TotalTime json.RawMessage `json:"total_time"`
}

type paths__1v2_1task_1_task_id__1time_in_status_get_responses_200_content_application_1json_schema_properties_current_status_properties_total_time struct {
	ByMinute int `json:"by_minute"`
	Since string `json:"since"`
}

type paths__1v2_1task_1_task_id__1time_in_status_get_responses_200_content_application_1json_schema_properties_status_history_items struct {
	Color string `json:"color"`
	Orderindex int `json:"orderindex"`
	Status string `json:"status"`
	TotalTime json.RawMessage `json:"total_time"`
	Type string `json:"type"`
}

type paths__1v2_1task_1_task_id__get_responses_200_content_application_1json_schema_properties_attachments_items_properties_user struct {
	Color string `json:"color"`
	Email string `json:"email"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	ProfilePicture string `json:"profilePicture"`
	Username string `json:"username"`
}

type paths__1v2_1task_1_task_id__get_responses_200_content_application_1json_schema_properties_creator struct {
	Color string `json:"color"`
	Email string `json:"email"`
	Id int `json:"id"`
	ProfilePicture string `json:"profilePicture"`
	Username string `json:"username"`
}

type paths__1v2_1task_1_task_id__get_responses_200_content_application_1json_schema_properties_custom_fields_items struct {
	DateCreated string `json:"date_created"`
	HideFromGuests bool `json:"hide_from_guests"`
	Id string `json:"id"`
	Name string `json:"name"`
	Required bool `json:"required"`
	Type string `json:"type"`
	TypeConfig json.RawMessage `json:"type_config"`
	Value string `json:"value"`
	ValueMarkdown string `json:"value_markdown"`
	ValueRichtext string `json:"value_richtext"`
}

type paths__1v2_1task_1_task_id__get_responses_200_content_application_1json_schema_properties_folder struct {
	Access bool `json:"access"`
	Hidden bool `json:"hidden"`
	Id string `json:"id"`
	Name string `json:"name"`
}

type paths__1v2_1task_1_task_id__get_responses_200_content_application_1json_schema_properties_list struct {
	Access bool `json:"access"`
	Id string `json:"id"`
	Name string `json:"name"`
}

type paths__1v2_1task_1_task_id__get_responses_200_content_application_1json_schema_properties_locations_items struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

type paths__1v2_1task_1_task_id__get_responses_200_content_application_1json_schema_properties_priority struct {
	Color string `json:"color"`
	Id string `json:"id"`
	Orderindex string `json:"orderindex"`
	Priority string `json:"priority"`
}

type paths__1v2_1task_1_task_id__get_responses_200_content_application_1json_schema_properties_space struct {
	Id string `json:"id"`
}

type paths__1v2_1task_1_task_id__get_responses_200_content_application_1json_schema_properties_status struct {
	Color string `json:"color"`
	Id string `json:"id"`
	Orderindex int `json:"orderindex"`
	Status string `json:"status"`
	Type string `json:"type"`
}

type paths__1v2_1team_1_team_Id__1task_get_responses_200_content_application_1json_schema_properties_tasks_items_properties_list struct {
	Access bool `json:"access"`
	Id string `json:"id"`
	Name string `json:"name"`
}

type paths__1v2_1team_1_team_Id__1time_entries_1start_post_requestBody_content_application_1json_schema_properties_tags_items struct {
	Name string `json:"name"`
}

type paths__1v2_1team_1_team_Id__1time_entries_get_responses_200_content_application_1json_schema_examples_0_data_0_approval struct {
	ApprovedAt int `json:"approved_at"`
	ApproverId int `json:"approver_id"`
	Approvers json.RawMessage `json:"approvers"`
	Data json.RawMessage `json:"data"`
	History json.RawMessage `json:"history"`
	Id string `json:"id"`
	Status string `json:"status"`
	User json.RawMessage `json:"user"`
	WorkspaceId int `json:"workspace_id"`
}

type paths__1v2_1team_1_team_Id__1time_entries_post_requestBody_content_application_1json_schema_properties_tags_items struct {
	Name string `json:"name"`
	TagBg string `json:"tag_bg"`
	TagFg string `json:"tag_fg"`
}

type paths__1v2_1team_1_team_id__1goal_get_responses_200_content_application_1json_schema_properties_goals_items_properties_members_items struct {
	Color string `json:"color"`
	Email string `json:"email"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	IsCreator bool `json:"isCreator"`
	PermissionLevel string `json:"permission_level"`
	ProfilePicture string `json:"profilePicture"`
	Username string `json:"username"`
}

type paths__1v2_1team_1_team_id__1guest_1_guest_id__put_responses_200_content_application_1json_schema_properties_guest_properties_user struct {
	Color string `json:"color"`
	CustomRole json.RawMessage `json:"custom_role"`
	DateInvited string `json:"date_invited"`
	DateJoined string `json:"date_joined"`
	Email string `json:"email"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	LastActive string `json:"last_active"`
	ProfilePicture string `json:"profilePicture"`
	Role int `json:"role"`
	Username string `json:"username"`
}

type paths__1v2_1team_1_team_id__1time_entries_1_timer_id__get_responses_200_content_application_1json_schema_properties_data_properties_task_location struct {
	FolderId int `json:"folder_id"`
	FolderName string `json:"folder_name"`
	ListId int `json:"list_id"`
	ListName string `json:"list_name"`
	SpaceId int `json:"space_id"`
	SpaceName string `json:"space_name"`
}

type paths__1v2_1team_1_team_id__1time_entries_1_timer_id__get_responses_200_content_application_1json_schema_properties_data_properties_task_tags_items struct {
	Creator int `json:"creator"`
	Name string `json:"name"`
	TagBg string `json:"tag_bg"`
	TagFg string `json:"tag_fg"`
}

type paths__1v2_1team_1_team_id__1time_entries_1stop_post_responses_200_content_application_1json_schema_properties_data struct {
	At int `json:"at"`
	Billable bool `json:"billable"`
	Description string `json:"description"`
	Duration int `json:"duration"`
	End int `json:"end"`
	Id string `json:"id"`
	Source string `json:"source"`
	Start string `json:"start"`
	Tags json.RawMessage `json:"tags"`
	Task json.RawMessage `json:"task"`
	User json.RawMessage `json:"user"`
	Wid string `json:"wid"`
}

type paths__1v2_1team_1_team_id__1time_entries_1stop_post_responses_200_content_application_1json_schema_properties_data_properties_task struct {
	CustomType string `json:"custom_type"`
	Id string `json:"id"`
	Name string `json:"name"`
	Status json.RawMessage `json:"status"`
}

type paths__1v2_1team_1_team_id__1user_1_user_id__delete_responses_200_content_application_1json_schema_properties_team struct {
	Avatar string `json:"avatar"`
	Color string `json:"color"`
	Id string `json:"id"`
	Members json.RawMessage `json:"members"`
	Name string `json:"name"`
}

type paths__1v2_1team_1_team_id__1user_1_user_id__get_responses_200_content_application_1json_schema_properties_member struct {
	InvitedBy json.RawMessage `json:"invited_by"`
	Shared json.RawMessage `json:"shared"`
	User json.RawMessage `json:"user"`
}

type paths__1v2_1team_1_team_id__1user_1_user_id__get_responses_200_content_application_1json_schema_properties_member_properties_invited_by struct {
	Color string `json:"color"`
	Email string `json:"email"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	ProfilePicture string `json:"profilePicture"`
	Username string `json:"username"`
}

type paths__1v2_1team_1_team_id__1user_1_user_id__get_responses_200_content_application_1json_schema_properties_member_properties_shared struct {
	Folders json.RawMessage `json:"folders"`
	Lists json.RawMessage `json:"lists"`
	Tasks json.RawMessage `json:"tasks"`
}

type paths__1v2_1team_1_team_id__1user_1_user_id__get_responses_200_content_application_1json_schema_properties_member_properties_user_properties_custom_role struct {
	Id int `json:"id"`
	Name string `json:"name"`
}

type paths__1v2_1team_1_team_id__1user_post_responses_200_content_application_1json_schema_properties_team_properties_roles_items struct {
	Custom bool `json:"custom"`
	Id int `json:"id"`
	InheritedRole int `json:"inherited_role"`
	Name string `json:"name"`
}

type paths__1v2_1team_get_responses_200_content_application_1json_schema_properties_teams_items_properties_members_items struct {
	User json.RawMessage `json:"user"`
}

type paths__1v2_1user_get_responses_200_content_application_1json_schema_properties_user struct {
	Color string `json:"color"`
	Email string `json:"email"`
	GlobalFontSupport bool `json:"global_font_support"`
	Id int `json:"id"`
	Initials string `json:"initials"`
	ProfilePicture string `json:"profilePicture"`
	Timezeone string `json:"timezeone"`
	Username string `json:"username"`
	WeekStartDay int `json:"week_start_day"`
}

type paths__1v2_1view_1_view_id__get_responses_200_content_application_1json_schema_oneOf_0 struct {
	View json.RawMessage `json:"view"`
}

type paths__1v2_1view_1_view_id__put_requestBody_content_application_1json_schema_properties_columns struct {
	Fields json.RawMessage `json:"fields"`
}

type paths__1v2_1view_1_view_id__put_requestBody_content_application_1json_schema_properties_divide struct {
	Collapsed json.RawMessage `json:"collapsed"`
	Dir string `json:"dir"`
	Field string `json:"field"`
}

type paths__1v2_1view_1_view_id__put_requestBody_content_application_1json_schema_properties_filters struct {
	Fields json.RawMessage `json:"fields"`
	Op string `json:"op"`
	Search string `json:"search"`
	ShowClosed bool `json:"show_closed"`
}

type paths__1v2_1view_1_view_id__put_requestBody_content_application_1json_schema_properties_grouping struct {
	Collapsed json.RawMessage `json:"collapsed"`
	Dir int `json:"dir"`
	Field string `json:"field"`
	Ignore bool `json:"ignore"`
}

type paths__1v2_1view_1_view_id__put_requestBody_content_application_1json_schema_properties_parent struct {
	Id string `json:"id"`
	Type int `json:"type"`
}

type paths__1v2_1view_1_view_id__put_requestBody_content_application_1json_schema_properties_settings struct {
	CollapseEmptyColumns string `json:"collapse_empty_columns"`
	MeChecklists bool `json:"me_checklists"`
	MeComments bool `json:"me_comments"`
	MeSubtasks bool `json:"me_subtasks"`
	ShowAssignees bool `json:"show_assignees"`
	ShowClosedSubtasks bool `json:"show_closed_subtasks"`
	ShowImages bool `json:"show_images"`
	ShowSubtaskParentNames bool `json:"show_subtask_parent_names"`
	ShowSubtasks int `json:"show_subtasks"`
	ShowTaskLocations bool `json:"show_task_locations"`
}

type paths__1v2_1view_1_view_id__put_requestBody_content_application_1json_schema_properties_sorting struct {
	Fields json.RawMessage `json:"fields"`
}

type paths__1v2_1view_1_view_id__put_requestBody_content_application_1json_schema_properties_team_sidebar struct {
	AssignedComments bool `json:"assigned_comments"`
	Assignees json.RawMessage `json:"assignees"`
	UnassignedTasks bool `json:"unassigned_tasks"`
}

type paths__1v2_1webhook_1_webhook_id__put_responses_200_content_application_1json_schema_properties_webhook struct {
	ClientId string `json:"client_id"`
	Endpoint string `json:"endpoint"`
	Events json.RawMessage `json:"events"`
	FolderId string `json:"folder_id"`
	Health json.RawMessage `json:"health"`
	Id string `json:"id"`
	ListId string `json:"list_id"`
	Secret string `json:"secret"`
	SpaceId string `json:"space_id"`
	TaskId string `json:"task_id"`
	TeamId int `json:"team_id"`
	Userid int `json:"userid"`
}
