// Copyright 2026 sidhartha1s. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTeamFieldCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "field",
		Short: "Manage field",
	}

	cmd.AddCommand(newTeamFieldGetTeamAvailableCmd(flags))
	return cmd
}
